### ISSUE TITLE
Give different sets of users different access to data

### ISSUE THREAD

**Issue by pindec** [open-contracting/kingfisher-views#1]
It would be helpful if we could provide different levels of access for different users.

E.g. to simplify queries for data journalists, just provide access to kingfisher-views tables for a subset of publishers.

**Comment by robredpath** [comment]
Internal issue - https://crm.open-contracting.org/issues/4351

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make it easier to create new read-only users for the hosted Kingfisher database](https://trello.com/c/BE9JOi2Z/133-make-it-easier-to-create-new-read-only-users-for-the-hosted-kingfisher-database)

**Comment by odscjames** [comment]
We need to strongly define what we need here. The technical work could vary a lot based on different requirements.

So far we have:

Split data into public and private. Have a way to create read only external database users to View only AND to public data only.

Any advances?

Public & Private - probably by marking collections in Kingfisher process?

Also, a solution for this might build on #31 so check that.

**Comment by pindec** [comment]
I think this will need to build on #31. 

If views do become generated in their own schemas to solve #31, e.g. view_collectionid or view_set_of_collection_ids, then this issue is about being able to generate a read-only user just for particular schemas.

The added complication there is that not all views contain the source data so schema-level-users might not be able to access all the raw JSON. @kindly is thinking about that as part of #31.

**Comment by robredpath** [comment]
As I understand it, there are two user stories here:

"As a researcher, **I want to** have access to a set of data that I can easily query **so that** I can understand government contracting in a particular context"
"As a Helpdesk analyst, **I want** to be able to give out credentials for a database of real OCDS data without worrying about accidentally exposing data that isn't yet public **so that** I can share resources more widely"

Does that match your understanding @pindec ?

**Comment by jpmckinney** [comment]
We've solved this for Views: https://kingfisher-views.readthedocs.io/en/latest/users.html. For Process, we can open an issue there as needed.
