### ISSUE TITLE
Date/time error when creating view

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/kingfisher-views#152]
Trying to run 

> ocdskingfisher-views-cli add-view 1512,1517,1515 ... 

Getting this error

> psycopg2.errors.DatetimeFieldOverflow: date/time field value out of range: "0000-04-30T13:46:38+01:00"

Looking at the log files, it's happening here

> Oct 22 12:25:11 process1 2020-10-22 12:25:11,429 - 13935 - ocdskingfisher.views.refresh-views - INFO - Running 007-contracts

Any ideas?

**Comment by jpmckinney** [comment]
@odscrachel I assume the source data might have a date value that is out of PostgreSQL's allowed range. I suppose a solution is for the query to filter out out-of-range dates. In that case, a note should perhaps be written to a table to let the user know that some dates were omitted from the aggregation.

**Comment by kindly** [comment]
This is due to dates starting with `0000` and for some reason postgresql does not like that year (it actually represents 1 BC)

We already exclude any non ISO looking dates from the results and null them.  I think it might be a separate issue to log these.  However, the idea was that these were going to be picked up as validation errors, so there was no need for separate log.

The validation errors could according to ISO be allowed to pick up on dates before 1583, see https://en.wikipedia.org/wiki/ISO_8601#Years.

**Comment by jpmckinney** [comment]
Instead of a separate log, I've just requested a sentence in the docs in the PR.

**Comment by jpmckinney** [comment]
Deployed #154. @odscrachel You can try again now.

**Comment by odscrachel** [comment]
Great, all is working fine now and view created. Thanks @kindly and @jpmckinney
