### ISSUE TITLE
Several queries use deprecated fields instead of parties array

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#45]
For example, `buyer_summary.buyer_identifier` is constructed from `buyer -> 'identifier' -> 'scheme'` and `buyer -> 'identifier -> 'id'.

Similarly, `procuringEntity_summary.procuringentity_identifier`, `tenderers_summary.tenderer_identifier` and `award_suppliers_summary.suppliers_identifier` are also constructed using the identifier block which has been deprecated outside the parties section.

This means that these fields are NULL for OCDS 1.1 data, e.g (from @camilamila):

> Using collection 193 (from Chile) with ocid = ocds-70d2nz-5413-181-L117:
> 
> views.parties_summary.identifier= CL-MercadoPublico-6326
> views.parties_summary.party.id= 70.772.100-6
> views.procuringEntity_summary.procuringentity_parties_id = 70.772.100-6
> views.procuringEntity_summary.procuringentity_identifier = NULL

@kindly I'm not sure if this was planned (for OCDS 1.0 support) or unintentional, but given that we upgrade all data to 1.1 in the process pipeline, I think these fields should be constructed from the organization identifier in the `parties` section.

Edit: This also applies to the `unique_identifier_attempt` fields for organization references.

**Comment by jpmckinney** [comment]
`award_suppliers_summary.supplier_additionalidentifiers_ids`, `award_suppliers_summary.supplier_additionalidentifiers_count` and likely others also read `additionalIdentifiers`, etc. from the `OrganizationReference` in `awards.suppliers` rather than from the `Organization` in `parties`.

**Comment by jpmckinney** [comment]
I think the solution is to join with `parties_summary`.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Views: Add new aggregates/fields](https://trello.com/c/1Ta2HPcR/105-views-add-new-aggregates-fields)

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Views: Several queries use deprecated fields instead of parties array](https://trello.com/c/sw1TVcsP/177-views-several-queries-use-deprecated-fields-instead-of-parties-array)

**Comment by kindly** [comment]
Yep we need to join to `parties` and we do just not getting the data from correct place.  We should probably only join if the `id` join is correct not the `unique_identifier_attempt`.

**Comment by jpmckinney** [comment]
@kindly Please re-read the `create table staged_award_suppliers_summary` statement, viz my comments in https://github.com/open-contracting/kingfisher-views/issues/45#issuecomment-593769081. My reading is that `supplier` is a OrganizationReference object in `awards.suppliers`, not an Organization object from `parties`.

**Comment by kindly** [comment]
@jpmckinney  sorry last message not clear.  I agree that it is currently wrong.

The information should probably got from `parties_summary` table.  There is a join to that table (in order to get `parties_index`) in those queries but the information is not got from there and is using the 1.0 deprecated fields.  This was by design.

The above point was about how we join to the `parties_summary` table.  Currently we are using the `id` field and but it is possible to join using `unique_identifier_attempt`. I still think we should just use the `id` field so the above changes should be easy as just referring to the already created fields in the `parties_summary` table instead.

I think the original idea was to leave it up to the analysts to see how they wanted to join to the `parties_summary` table (using either `parties_index` or `unique_identifier_attempt`).   As that was the main use of `unique_identifier_attempt` in the first place.   This was when lots of people were doing `parties` badly.

**Comment by Bjwebb** [comment]
It looks like it's going to be fairly easy to maintain 1.0 compatibility (fall back to the old query), is this worth doing? The kingfisher live server upgrades data to 1.1, but it looks like our vagrant dev setup doesn't out of the box (an alternative could be to change that).

**Comment by jpmckinney** [comment]
I don't think we need to support 1.0. I think it's fine to require that data be upgraded, which users can either do via Kingfisher Process's transforms, or by using OCDS Kit or Toucan before local-loading into Kingfisher Process.
