### ISSUE TITLE
Create *_with_collection views

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#62]
Continuing discussion from https://github.com/open-contracting/kingfisher-process/issues/236

Views depends on Process, insofar as any change to Process' database schema can break Views (see https://github.com/open-contracting/kingfisher-process/issues/187 for a discussion of how to mitigate that).

As of https://github.com/open-contracting/kingfisher-process/issues/236 (PR https://github.com/open-contracting/kingfisher-process/issues/255), `collection_id` is available on the `record`, `release` and `compiled_release` tables.

As such, the `*_with_collection` tables are deprecated, but should be kept around as notebooks, etc. might expect them. We can keep the deprecated views in Process. However, since all other views are in Views, I think it makes more sense to keep them here.

For now, these views will continue to exist until we drop the database or move to a new server, so there is no urgency to write a migration or script to re-create them.

**Comment by odscjames** [comment]
>  However, since all other views are in Views,

I don't think this follows? 

The name of views is just a name (and it turns out, a badly chosen name, as we already have confusion between a "view" as a postgres object like a table but not, and "view" a collection of tables and views which hold data on a collection, of which you used to only have one that was rebuilt evey night whether it needed it or not, and now you can have many, to avoid excessive rebuilding and allow instant triggering, and which we call "view" but postgres calls "schema".)

We should be instead keeping code in the most relevant place. The code that created these views is in Process, and I think we should deal with them there. Having a view created in one app but deleted/modified in another app makes for confusing code and odd race conditions around different install situations.

> For now, these views will continue to exist until we drop the database

That's not true, I think.

Both Currently - and when https://github.com/open-contracting/kingfisher-process/pull/255 is merged - the database migrations in Process will create the views but nothing will delete them. So any third party spinning up this app will get the views.

### What I think we should do with *_with_collection views:

Just leave them. My understanding of Postgres internals is that if no-one queries these views, there will be no extra load on the server. Give the analysts plenty of time to move to using the new tables, there's no need to rush them. 

Also - we could redefine them to not have joins any more - the definition becomes a simple select. That way, I think the performance of queries is basically the same, whether someone uses "release" or "release_with_collection".

(But I think any redefinition should happen in the "Process" app.)

### What we need to do in "views" app tho

https://github.com/open-contracting/kingfisher-views/blob/master/sql/002-tmp_release_and_parties.sql has reference to *_with_collection views - we should change these in a bit.

**Comment by jpmckinney** [comment]
I made a PR so that Process no longer creates the views: https://github.com/open-contracting/kingfisher-process/pull/256

I'm happy if that PR is merged and nothing further happens. If it's merged, the views will remain available for analysts – unless we drop the database and restart from scratch. If so (very unlikely) we can still just manually run the SQL in https://github.com/open-contracting/kingfisher-process/blob/98fecdcf49212bec5562b44d35e371325aafc1dc/ocdskingfisherprocess/maindatabase/migrations/versions/aef60ba6c0bc_view.py to re-create the views.

If, at a later date, we want to clean up the database, we can drop the views.

**Comment by odscjames** [comment]
I think this is almost ready for closing when PR done?
