### ISSUE TITLE
Quote schema names

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-views#78]
Instead of repetitive comments about why SQL injection is okay, we should just have a few more characters of source code and do it properly:

~~https://docs.sqlalchemy.org/en/13/core/sqlelement.html#sqlalchemy.sql.expression.text~~

**Comment by kindly** [comment]
`text` will not work for the cases commented.  This is because we are trying to parametrise schema names not strings, ints, numbers etc.

There is not particularly nice way to do this.  The "correct" way is call quote_ident https://www.psycopg.org/docs/extensions.html?highlight=quote_ident#psycopg2.extensions.quote_ident and add that to the raw string but this requires a database connection to ask for the correct quoting.

**Comment by jpmckinney** [comment]
Ah, right. I think the simplest way to do it is #103.
